import { App, MarkdownPostProcessorContext, TFile, MarkdownRenderChild } from "obsidian";
import { SankeyParser } from "./SankeyParser";
import { SankeyRenderer } from "./SankeyRenderer";
import { FinkeySettings } from "./FinkeySettings";

class FinkeyRenderChild extends MarkdownRenderChild {
    private cleanupFn?: () => void;

    constructor(
        containerEl: HTMLElement,
        private app: App,
        private source: string,
        private ctx: MarkdownPostProcessorContext,
        private settings: FinkeySettings
    ) {
        super(containerEl);
    }

    onload() {
        this.containerEl.empty();

        try {
            const parsedData = SankeyParser.parse(this.source);

            const onDragEnd = async (positions: Record<string, { x: number, y: number }>) => {
                // get line numbers of code block
                const sectionInfo = this.ctx.getSectionInfo(this.containerEl);
                if (!sectionInfo) return;

                const file = this.app.vault.getAbstractFileByPath(this.ctx.sourcePath);
                if (!(file instanceof TFile)) return;

                const warningString = `// --- hic sunt dracones --- positional logic generated by finkey --`;
                const positionString = `// @positions: ${JSON.stringify(positions)}`;

                await this.app.vault.process(file, (data) => {
                    // convert .md string into array of lines
                    const lines = data.split('\n');
                    const blockStart = sectionInfo.lineStart;

                    // dynamically find last line to prevent stale cache
                    let blockEnd = blockStart;
                    while (blockEnd < lines.length) {
                        if (blockEnd > blockStart && lines[blockEnd]?.trim().startsWith('```')) {
                            break;
                        }
                        blockEnd++;
                    }

                    // isolate lines of this specific code block
                    const blockLines = lines.slice(blockStart, blockEnd + 1);

                    const existingIndex = blockLines.findIndex(line => line.trim().startsWith('// @positions:'));
                    if (existingIndex !== -1) {
                        if (existingIndex > 0 && blockLines[existingIndex - 1]?.trim() === warningString) {
                            // Warning already in place
                            blockLines[existingIndex] = positionString;
                        } else {
                            blockLines.splice(existingIndex, 1, "", warningString, positionString);
                        }
                    } else {
                        // Insert it right before the final closing ```
                        blockLines.splice(blockLines.length - 1, 0, "", warningString, positionString);
                    }

                    lines.splice(blockStart, blockEnd - blockStart + 1, ...blockLines);
                    return lines.join('\n');
                });
            };

            this.cleanupFn = SankeyRenderer.render(parsedData, this.containerEl, this.settings, onDragEnd);

        } catch (error) {
            this.containerEl.createDiv({
                text: `Finkey Error: ${error instanceof Error ? error.message : 'Unknown error'}`,
                attr: { style: "color: var(--text-error); font-weight: bold;" }
            });
        }
    }
    onunload() {
        if (this.cleanupFn) {
            this.cleanupFn();
        }
    }
}

export class SankeyProcessor {
    constructor(
        private app: App,
        private settings: FinkeySettings
    ) {}
    public process(source: string, el: HTMLElement, ctx: MarkdownPostProcessorContext) {
        const renderChild = new FinkeyRenderChild(el, this.app, source, ctx, this.settings);

        // hand it over to obsidians lifecycle manager
        ctx.addChild(renderChild);
    }
}